<?php

/**
 * @file
 * Contains xmlsitemap_extend.module file.
 */

use Drupal\node\Entity\Node;

/**
 * Implements hook_simple_sitemap_links_alter().
 *
 * Excludes nodes from the sitemap if a specific field value is set.
 */
function xmlsitemap_extend_xmlsitemap_link_alter(array &$link) {

  if ($link['type'] == 'node') {
    $node = Node::load($link['id']);

    if ($node && $node->hasField("field_model") && !$node->get("field_model")->isEmpty()) {
      $referenced_entities = $node->get("field_model")->referencedEntities();

      if (!empty($referenced_entities)) {
        $first_entity = $referenced_entities[0];
        $entity_label = $first_entity->label();
        if ($entity_label == "Page") {
          $link['status'] = 0;
          // Safety measure.
          $link['access'] = 0;
        }
      }

    }
  }

}
